###############################################################################
##
## Additional pattern rules
##
###############################################################################

# Generate parser/lexer code from Antlr grammar files
$(gen_srcdir)/%Lexer.hpp : io/%.g
	java antlr.Tool -o $(gen_srcdir) $<
$(gen_srcdir)/%Parser.hpp : io/%.g
	java antlr.Tool -o $(gen_srcdir) $<
%Lexer.cpp : %Lexer.hpp
%Parser.cpp : %Parser.hpp
