# Get the construction environment from the parent script
Import('env')

objs = []

# Use a precompiled header on toolchains that support it
env = env.Clone()
pch = env.PCH('precomp.cpp')
env['PCH'] = pch[0]
env['PCHSTOP'] = 'inca/precomp.h'
objs += [pch[1]]

objs += env.SConscript(dirs = ['util', 'world', 'integration', 'ui'], exports = { 'env' : env })

env.StaticLibrary('inca', objs)
